import { ApolloProvider } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import client from "./apollo-client";
import CardLink from "./components/post/CardLink";
import CurvedText from "./components/post/CurvedText";
import PostList from "./components/post/List";

const Home: NextPage = () => {
  return (
    <ApolloProvider client={client}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <CardLink />
          <CurvedText />
          <PostList />
        </main>
      </div>
    </ApolloProvider>
  );
};

export default Home;
