import type { NextPage } from "next";
import Head from "next/head";
import CardLink from "../components/post/CardLink";
import CurvedText from "../components/post/CurvedText";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CardLink />
        <CurvedText />
      </main>
    </div>
  );
};

export default Home;
